/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type PostResponse = {
  title: string;
  content: string;
  id: number;
};

export type PostDto = {
  title: string;
  content: string;
};
